export const phrases = {
  ru: [
    "Осваиваю мир кода и технологий",
    "Учусь создавать цифровое будущее",
    "Погружаюсь в IT и инженерию",
    "Строю цифровое завтра",
    "Изучаю магию программирования",
    "Превращаю код в возможности",
    "Осваиваю full-stack разработку",
    "Создаю цифровые впечатления",
    "Пишу код, формируя будущее",
    "Ищу новые горизонты в IT",
    "Решаю сложные задачи с помощью кода",
    "Превращаю идеи в работающие программы",
    "Постоянно учусь и развиваюсь в IT",
    "Работаю с данными, извлекая смысл",
    "Проектирую интуитивные интерфейсы",
    "Автоматизирую процессы, упрощая жизнь",
    "Сочетаю логику и творчество в разработке",
    "Вношу вклад в мир технологий",
    "Постоянно ищу способ сделать код чище",
    "Код — это мое хобби и работа",
    "Ищу идеальный баланс между красотой и функциональностью",
    "Вдохновляюсь новыми проектами",
    "Работаю над улучшением пользовательского опыта",
    "Изучаю лучшие практики разработки",
    "Стремлюсь к созданию качественного кода",
    "Адаптирую технологии под реальные задачи",
    "Стремлюсь к постоянному профессиональному росту",
    "Развиваю навыки веб-разработки",
    "Экспериментирую с креативными решениями",
    "Нахожу красоту в простых и элегантных решениях"
  ],
  en: [
    "Exploring the world of code and technology",
    "Learning to create the digital future",
    "Diving into IT and engineering",
    "Building digital tomorrow",
    "Studying the magic of programming",
    "Transforming code into opportunities",
    "Mastering full-stack development",
    "Crafting digital experiences",
    "Writing code, shaping the future",
    "Seeking new horizons in IT",
    "Solving complex problems with code",
    "Turning ideas into working programs",
    "Continuously learning and growing in IT",
    "Working with data, extracting meaning",
    "Designing intuitive interfaces",
    "Automating processes, simplifying life",
    "Combining logic and creativity in development",
    "Contributing to the world of technology",
    "Constantly seeking cleaner code",
    "Code is my hobby and job",
    "Finding the sweet spot between design and function",
    "Inspired by the next great project",
    "Working on user experience improvement",
    "Studying development best practices",
    "Striving for high-quality code",
    "Adapting technologies to real-world tasks",
    "Striving for continuous professional growth",
    "Developing web development skills",
    "Experimenting with creative solutions",
    "Finding beauty in simple and elegant solutions"
  ]
}
