import IconReact from '../icons/skilsForCards/IconReact/IconReact';
import IconJS from '../icons/skilsForCards/IconJS/IconJS';
import IconZustand from '../icons/skilsForCards/IconZustand/IconZustand';
import IconHTML from '../icons/skilsForCards/IconHTML/IconHTML';
import IconCSS from '../icons/skilsForCards/IconCSS/IconCSS';
import IconSCSS from '../icons/skilsForCards/IconSCSS/IconSCSS';
import IconPixo from '../icons/skilsForCards/IconPixo/IconPixo';
import IconFigma from '../icons/skilsForCards/IconFigma/IconFigma';
import IconAdobePhotoshop from '../icons/skilsForCards/IconAdobePhotoshop/IconAdobePhotoshop';
import IconJQuery from '../icons/skilsForCards/IconJQuery/IconJQuery';

//  [IconReact, IconJS, IconZustand, IconHTML, IconCSS, IconSCSS, IconPixo, IconFigma, IconAdobePhotoshop, IconJQuery,]

// title_en - полная версия заголовка
// mobile_title_en - может быть короткой версией заголовка для того, чтобы помещалась в хедере карточки-аккордиона
// header_title_short_en - короткая версия для шапки-хедера('PageTitlrs') в самом верху страниц

const projects = [
    { 
        id: 7,
        slug: 'roman-numerals-converter',
        title_en: 'Roman Numerals Converter',
        title_ru: 'Конвертер Римских Чисел',
        mobile_title_en: 'Roman Numerals Converter',
        mobile_title_ru: 'Конвертер Римских Чисел',
        header_title_short_en: 'Converter',
        header_title_short_ru: 'Конвертер',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/7-roman_numerals_converter.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS, ],
        description_en: 'Roman Numerals Converter description.',
        description_ru: 'Конвертер Римских Чисел описание',
        demo: 'https://mikevorobyev.github.io/Roman_Numerals_Converter/',
        gitHubLink: 'https://github.com/MikeVorobyev/Roman_Numerals_Converter',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 6,
        slug: 'to-do',
        title_en: 'To Do',
        title_ru: 'To Do',
        mobile_title_en: 'To Do',
        mobile_title_ru: 'To Do',
        header_title_short_en: 'To Do',
        header_title_short_ru: 'To Do',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/6-to_do.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS, ],
        description_en: 'To Do description.',
        description_ru: 'To Do описание',
        demo: 'https://mikevorobyev.github.io/to_do/',
        gitHubLink: 'https://github.com/MikeVorobyev/to_do',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 5,
        slug: 'dental-tooth',
        title_en: 'Dental Tooth',
        title_ru: 'Dental Tooth',
        mobile_title_en: 'Dental Tooth',
        mobile_title_ru: 'Dental Tooth',
        header_title_short_en: 'Dental Tooth',
        header_title_short_ru: 'Dental Tooth',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/5-dental_tooth.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS, IconJQuery, IconFigma, IconAdobePhotoshop, ],
        description_en: 'Dental Tooth description.',
        description_ru: 'Dental Tooth описание',
        demo: 'https://mikevorobyev.github.io/Dental_Tooth/',
        gitHubLink: 'https://github.com/MikeVorobyev/Dental_Tooth',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 4,
        slug: 'ui-kit',
        title_en: 'Ui Kit',
        title_ru: 'Ui Kit',
        mobile_title_en: 'Ui Kit',
        mobile_title_ru: 'Ui Kit',
        header_title_short_en: 'Ui Kit',
        header_title_short_ru: 'Ui Kit',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/4-ui_kit.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconFigma, ],
        description_en: 'Ui Kit description. Расскажи в видео, что кнопки из этого ui kit ты спользовал в проекте с римскими цифрами',
        description_ru: 'Ui Kit описание',
        demo: 'https://mikevorobyev.github.io/ui_kit/',
        gitHubLink: 'https://github.com/MikeVorobyev/ui_kit',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 3,
        slug: 'Organic-Juicy-Co',
        title_en: 'Organic Juicy Co',
        title_ru: 'Organic Juicy Co',
        mobile_title_en: 'Organic Juicy Co',
        mobile_title_ru: 'Organic Juicy Co',
        header_title_short_en: 'Juicy',
        header_title_short_ru: 'Juicy',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/3-organic_juicy_co.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS, IconFigma, ],
        description_en: 'Organic Juicy Co description',
        description_ru: 'Organic Juicy Co описание',
        demo: 'https://mikevorobyev.github.io/Organic_Juicy_Co/',
        gitHubLink: 'https://github.com/MikeVorobyev/Organic_Juicy_Co',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 2,
        slug: 'oculus', 
        title_en: 'Oculus',
        title_ru: 'Oculus',
        mobile_title_en: 'Oculus',
        mobile_title_ru: 'Oculus',
        header_title_short_en: 'Oculus',
        header_title_short_ru: 'Oculus',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/2-oculus.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS, IconFigma, IconAdobePhotoshop, ],
        description_en: 'Oculus description',
        description_ru: 'Oculus описание',
        demo: 'https://mikevorobyev.github.io/oculus/',
        gitHubLink: 'https://github.com/MikeVorobyev/oculus',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
    { 
        id: 1,
        slug: 'simple-calculator', 
        title_en: 'Simple Calculator',
        title_ru: 'Простой калькулятор',
        mobile_title_en: 'Simple Calculator',
        mobile_title_ru: 'Простой Калькулятор',
        header_title_short_en: 'Calculator',
        header_title_short_ru: 'Калькулятор',
        subtitle_en: 'Frontend',
        subtitle_ru: 'Frontend',
        screenshot: require('../../images/projects_images/image_portfolio/1-simple-calculator.jpg'),
        iconSkills: [ IconHTML, IconCSS, IconJS ],
        description_en: 'Simple Calculator description',
        description_ru: 'Простой калькулятор описание',
        demo: 'https://mikevorobyev.github.io/simple-calculator-/',
        gitHubLink: 'https://github.com/MikeVorobyev/simple-calculator-',
        videoYouTube: 'https://www.youtube.com/embed/QlPuT0hry2Y',
        videoRuTube: 'https://rutube.ru/play/embed/95a07e89c17ef6d847338afa312f3ccc/',
        mainFeatures: [
            { 
                featuresTitle_en: 'Pumpkin:', 
                featuresTitle_ru: 'Заглушка:', 
                featuresDescription_en: 'Pumpkin text',  
                featuresDescription_ru: 'Заглушка текст', 
            },
        ],
    },
];

export default projects
